default_platform(:ios)

platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(workspace: "MySight.xcworkspace",
                        scheme: "AppStoreScreenshots",
                        dark_mode: true)

    frame_screenshots
  end
end
