default_platform(:ios)

platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(workspace: "MySight.xcworkspace",
                        scheme: "AppStoreScreenshots",
                        dark_mode: false,
                        number_of_retries: 2)

    frame_screenshots

    deliver(username: "warren@apokrupto.com",
            overwrite_screenshots: true,
            force: true)
  end
end
