# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPhone 8",
  "iPhone 8 Plus",
  "iPhone SE (2nd generation)",
  "iPhone 13",
  "iPhone 13 Pro",
  "iPhone 13 Pro Max",
  "iPad (9th generation)",
  "iPad Air (4th generation)",
  "iPad Pro (12.9-inch) (5th generation)",
  "iPad Pro (11-inch) (3rd generation)",
  "iPad Pro (9.7-inch)",
])

languages([
  "en",
  "en-GB",
])

# The name of the scheme which contains the UI Tests
scheme("AppStoreScreenshots")

# Where should the resulting screenshots be stored?
output_directory("./fastlane/screenshots")

# remove the '#' to clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

# Remove the '#' to set the status bar to 9:41 AM, and show full battery and reception.
override_status_bar(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot
